### ISSUE TITLE
Unable to Install, Version Satisfiable

### ISSUE THREAD

**Issue by fer-ri** [mitchellvanw/hashids#12]
Hi, 

i've put my require like this '' mitch/hashids": "dev-master" ''
but the result error like this when running composer update

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Removal request for hashids/hashids == 0.3.9999999.9999999-dev
>     - Removal request for hashids/hashids == 9999999-dev
>     - mitch/hashids dev-master requires hashids/hashids \* -> satisfiable by hashids/hashids[0.3.x-dev, dev-master].
>     - Installation request for mitch/hashids dev-master -> satisfiable by mitch/hashids[dev-master].

**Comment by ludo237** [comment]
It seems that no one will update this repo, you should check some forks

**Comment by fer-ri** [comment]
Finally, i just use Hashids without ane facade or service provider

thanks

**Comment by mitchellvanw** [comment]
Yea, sorry about this. I updated the repo and added something sweat!
You can inject a Hashids instance now: https://github.com/mitchellvanw/hashids#injecting-hashids

**Comment by fer-ri** [comment]
Thanks :)

On 3 February 2014 07:26, Mitchell van Wijngaarden <notifications@github.com
