### ISSUE TITLE
App Key accessed incorrectly in HashidsServiceProvider

### ISSUE THREAD

**Issue by cubicleWar** [mitchellvanw/hashids#13]
The latest commit results in the following error when trying to use hashids :

log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Cannot use object of type Mitch\Hashids\HashidsServiceProvider as array'

I believe this can be fixed by changing $me['config'] to $me->app['config'] on line 33 in HashidsServiceProvider.php (assuming you meant to use the Laravel app key as the hashids salt).

**Comment by mitchellvanw** [comment]
Fixed.
