### ISSUE TITLE
Composer Errors

### ISSUE THREAD

**Issue by alexleonard** [mitchellvanw/hashids#15]
Hey there,

If I set composer require as:

`"mitch/hashids": "1.x"`

I get this error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mitch/hashids could not be found in any version, there may be a typo in the package name.
```

If I use `"mitch/hashids": "1.*@dev"`

Then I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mitch/hashids 1.*@dev -> satisfiable by mitch/hashids[1.x-dev].
    - mitch/hashids 1.x-dev requires hashids/hashids 0.3.x -> no matching package found.
```

**Comment by lokielse** [comment]
+1

**Comment by alexleonard** [comment]
I found out what was going on!

You need to set your composer file to 

```
"minimum-stability": "dev"
```

This will then work, but obviously you may not want to start using dev versions of all your other packages so make sure to also set the following option in composer.json

```
"prefer-stable": true
```

**Comment by korayguclu** [comment]
@alexleonard your solution is working for me. thanks
