### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by MichMich** [mitchellvanw/hashids#6]
Composer seems unable to upgrade this package.

  Problem 1
    - mitch/hashids dev-master requires hashids/hashids 0.3._@dev -> no matching package found.
    - mitch/hashids dev-master requires hashids/hashids 0.3._@dev -> no matching package found.
    - Installation request for mitch/hashids dev-master -> satisfiable by mitch/hashids[dev-master].

Any idea how to solve this? Thanks!

**Comment by jd327** [comment]
Hi, I'll let @mitchellvanw answer this one, but just FYI, composer package had a minor update, and require statement has changed:

"hashids/hashids": "dev-master"

_Edit:_ Current version is 0.3.1
