### ISSUE TITLE
Problems loading config

### ISSUE THREAD

**Issue by MichMich** [mitchellvanw/hashids#8]
Unfortunatly i'm unable to load hashids, the following error occurs.

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Using $this when not in object context

The error occurs on line 45 of HashidsServiceProvider.php.
I was able to fix (workaround) this, bij replacing line 45 by:

return \Config::get('hashids::salt');

Any idea why this error occurs?

**Comment by mitchellvanw** [comment]
Updated the repo! Also checkout this https://github.com/mitchellvanw/hashids#injecting-hashids
