### ISSUE TITLE
Compability for PHP 5.3.*

### ISSUE THREAD

**Issue by hisorange** [mitchellvanw/hashids#9]
```
Call to protected method Mitch\Hashids\HashidsServiceProvider::getSalt() from context
```

This happens on my webserver which uses php 5.3.17, not sure when it was fixed.

Explanation:
http://www.php.net/manual/en/functions.anonymous.php#98384

Currently I replaced the functions to public to fix the issue, but not sure that a pullable idea.

**Comment by ludo237** [comment]
Still the same problem, Maybe public method is the best solution ....

**Comment by mitchellvanw** [comment]
This should be fixed now
